### ISSUE TITLE
Pause rendering on non-focused tabs

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EMBL-EBI-Live-data-map#2]
The best bet is the Page Visibility API: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

Note this is only supported in IE10+, so we'd likely need to do a feature detection.

**Comment by pwalter-ebi** [comment]
https://github.com/mathiasbynens/jquery-visibility

**Comment by khawkins98** [comment]
This has been implemented: https://github.com/ebiwd/EMBL-EBI-Live-data-map/commit/97d2c86fbf2a1d521f7328f9c31785e15f0f167a
